//! `EV` event and `ERR` subsystem name tables, mirroring ArduPilot's
//! `Log_Event` and `LogErrorSubsystem` enumerations. IDs absent here are
//! rendered as their number.

pub(super) fn event_name(id: u8) -> Option<&'static str> {
    Some(match id {
        7 => "AP_STATE",
        9 => "INIT_SIMPLE_BEARING",
        10 => "ARMED",
        11 => "DISARMED",
        15 => "AUTO_ARMED",
        17 => "LAND_COMPLETE_MAYBE",
        18 => "LAND_COMPLETE",
        19 => "LOST_GPS",
        21 => "FLIP_START",
        22 => "FLIP_END",
        25 => "SET_HOME",
        26 => "SET_SIMPLE_ON",
        27 => "SET_SIMPLE_OFF",
        28 => "NOT_LANDED",
        29 => "SET_SUPERSIMPLE_ON",
        30 => "AUTOTUNE_INITIALISED",
        31 => "AUTOTUNE_OFF",
        32 => "AUTOTUNE_RESTART",
        33 => "AUTOTUNE_SUCCESS",
        34 => "AUTOTUNE_FAILED",
        35 => "AUTOTUNE_REACHED_LIMIT",
        36 => "AUTOTUNE_PILOT_TESTING",
        37 => "AUTOTUNE_SAVEDGAINS",
        38 => "SAVE_TRIM",
        39 => "SAVEWP_ADD_WP",
        41 => "FENCE_ENABLE",
        42 => "FENCE_DISABLE",
        43 => "ACRO_TRAINER_OFF",
        44 => "ACRO_TRAINER_LEVELING",
        45 => "ACRO_TRAINER_LIMITED",
        46 => "GRIPPER_GRAB",
        47 => "GRIPPER_RELEASE",
        49 => "PARACHUTE_DISABLED",
        50 => "PARACHUTE_ENABLED",
        51 => "PARACHUTE_RELEASED",
        52 => "LANDING_GEAR_DEPLOYED",
        53 => "LANDING_GEAR_RETRACTED",
        54 => "MOTORS_EMERGENCY_STOPPED",
        55 => "MOTORS_EMERGENCY_STOP_CLEARED",
        56 => "MOTORS_INTERLOCK_DISABLED",
        57 => "MOTORS_INTERLOCK_ENABLED",
        58 => "ROTOR_RUNUP_COMPLETE",
        59 => "ROTOR_SPEED_BELOW_CRITICAL",
        60 => "EKF_ALT_RESET",
        61 => "LAND_CANCELLED_BY_PILOT",
        62 => "EKF_YAW_RESET",
        63 => "AVOIDANCE_ADSB_ENABLE",
        64 => "AVOIDANCE_ADSB_DISABLE",
        65 => "AVOIDANCE_PROXIMITY_ENABLE",
        66 => "AVOIDANCE_PROXIMITY_DISABLE",
        67 => "GPS_PRIMARY_CHANGED",
        68 => "WINCH_RELAXED",
        69 => "WINCH_LENGTH_CONTROL",
        70 => "WINCH_RATE_CONTROL",
        71 => "ZIGZAG_STORE_A",
        72 => "ZIGZAG_STORE_B",
        73 => "LAND_REPO_ACTIVE",
        74 => "STANDBY_ENABLE",
        75 => "STANDBY_DISABLE",
        80 => "FENCE_FLOOR_ENABLE",
        81 => "FENCE_FLOOR_DISABLE",
        85 => "EK3_SOURCES_SET_TO_PRIMARY",
        86 => "EK3_SOURCES_SET_TO_SECONDARY",
        87 => "EK3_SOURCES_SET_TO_TERTIARY",
        90 => "AIRSPEED_PRIMARY_CHANGED",
        163 => "SURFACED",
        164 => "NOT_SURFACED",
        165 => "BOTTOMED",
        166 => "NOT_BOTTOMED",
        _ => return None,
    })
}

pub(super) fn error_subsystem_name(id: u8) -> Option<&'static str> {
    Some(match id {
        1 => "MAIN",
        2 => "RADIO",
        3 => "COMPASS",
        4 => "OPTFLOW",
        5 => "FAILSAFE_RADIO",
        6 => "FAILSAFE_BATT",
        7 => "FAILSAFE_GPS",
        8 => "FAILSAFE_GCS",
        9 => "FAILSAFE_FENCE",
        10 => "FLIGHT_MODE",
        11 => "GPS",
        12 => "CRASH_CHECK",
        13 => "FLIP",
        14 => "AUTOTUNE",
        15 => "PARACHUTES",
        16 => "EKFCHECK",
        17 => "FAILSAFE_EKFINAV",
        18 => "BARO",
        19 => "CPU",
        20 => "FAILSAFE_ADSB",
        21 => "TERRAIN",
        22 => "NAVIGATION",
        23 => "FAILSAFE_TERRAIN",
        24 => "EKF_PRIMARY",
        25 => "THRUST_LOSS_CHECK",
        26 => "FAILSAFE_SENSORS",
        27 => "FAILSAFE_LEAK",
        28 => "PILOT_INPUT",
        29 => "FAILSAFE_VIBE",
        30 => "INTERNAL_ERROR",
        31 => "FAILSAFE_DEADRECKON",
        _ => return None,
    })
}
