[package]
name = "delog-api"
description = "DeLOG native data and application control API"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
arrow = { workspace = true }
delog-core = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
